name: Integration Test CI

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  integration-test:
    runs-on: ubuntu-latest
    env:
      SMTP_HOST: ${{ secrets.SMTP_HOST }}
      SMTP_USER: ${{ secrets.SMTP_USER }}
      SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
      SMTP_PORT: ${{ secrets.SMTP_PORT }}
      IS_TESTING: "true"

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install Dependencies
        run: npm ci

      - name: Set up and download Docker Compose
        uses: docker/setup-compose-action@v1.2.0
        with:
          version: latest

      - name: docker-compose up
        run: |
          docker-compose up -d

      - name: Wait for backend to be healthy
        run: |
          echo "Waiting for backend health..."
          sleep 10  
          for i in {1..20}; do
              if curl -f http://localhost:5171/health; then
                echo "Backend is healthy"
                exit 0
              fi
              sleep 5  
          done
          echo "Backend never became healthy"
          docker-compose logs 
          exit 1

      - name: Run Integration Tests
        run: npm run test:integration

      - name: Stop docker-compose and clean up
        run: |
          docker-compose down --volumes --remove-orphans
